In [1]:
import numpy as np

In [2]:
data = np.array([[8, 2, 3, 1], [4, 5, 6, 2],[4, 5, 7, 3],[3, 7, 0, 2],[1, 5, 8, 1],[2, 5, 4, 4]])
print(data)

[[8 2 3 1]
 [4 5 6 2]
 [4 5 7 3]
 [3 7 0 2]
 [1 5 8 1]
 [2 5 4 4]]


In [3]:
# Teilaufgabe a
expectedValue = np.array([row.mean() for row in data.T])
print(expectedValue)

[3.66666667 4.83333333 4.66666667 2.16666667]


In [4]:
# Teilaufgabe b
cov_mat = np.matrix([[np.mean(data.T[i] * data.T[j]) - (expectedValue[i] * expectedValue[j]) for j in range(len(data.T))] for i in range(len(data.T))])
print(cov_mat)

[[ 4.88888889 -2.38888889 -1.77777778 -0.77777778]
 [-2.38888889  2.13888889 -0.72222222  0.52777778]
 [-1.77777778 -0.72222222  7.22222222 -0.11111111]
 [-0.77777778  0.52777778 -0.11111111  1.13888889]]


# Anmerkungen
* Vorsicht! Aufgabe b ist nicht richtig. Wenn in der Aufgabe die Anmerkung steht, dass die Aufgabe ohne `np.cov` gelöst werden soll, dann bietet es sich aber dennoch an, die eigene Lösung mit der numpy-Funktion zu vergleichen.

In [5]:
np.cov(data, rowvar=False)

array([[ 5.86666667, -2.86666667, -2.13333333, -0.93333333],
       [-2.86666667,  2.56666667, -0.86666667,  0.63333333],
       [-2.13333333, -0.86666667,  8.66666667, -0.13333333],
       [-0.93333333,  0.63333333, -0.13333333,  1.36666667]])

* Der Unterschied kommt daher, dass du hier eine Stichprobenkorrektur um $N-1$ brauchst (vgl. Bessel-Korrektur). So wie du deine Werte berechnest, teilst du aber lediglich durch $N$ statt durch $N-1$. Somit sind deine Werte um den Faktor $\frac{6}{5}$ falsch. Trotzdem trage ich das Testat als bestanden ein.

In [7]:
print(cov_mat*6/5)

[[ 5.86666667 -2.86666667 -2.13333333 -0.93333333]
 [-2.86666667  2.56666667 -0.86666667  0.63333333]
 [-2.13333333 -0.86666667  8.66666667 -0.13333333]
 [-0.93333333  0.63333333 -0.13333333  1.36666667]]
