In [1]:
import numpy as np

In [2]:
data = np.array([[8, 2, 3, 1], [4, 5, 6, 2],[4, 5, 7, 3],[3, 7, 0, 2],[1, 5, 8, 1],[2, 5, 4, 4]])
print(data)

[[8 2 3 1]
 [4 5 6 2]
 [4 5 7 3]
 [3 7 0 2]
 [1 5 8 1]
 [2 5 4 4]]


In [3]:
# Teilaufgabe a
expectedValue = np.array([row.mean() for row in data.T])
print(expectedValue)

[3.66666667 4.83333333 4.66666667 2.16666667]


In [4]:
# Teilaufgabe b
np.matrix([[np.mean(data.T[i] * data.T[j]) - (expectedValue[i] * expectedValue[j]) for j in range(len(data.T))] for i in range(len(data.T))])

matrix([[ 4.88888889, -2.38888889, -1.77777778, -0.77777778],
        [-2.38888889,  2.13888889, -0.72222222,  0.52777778],
        [-1.77777778, -0.72222222,  7.22222222, -0.11111111],
        [-0.77777778,  0.52777778, -0.11111111,  1.13888889]])